# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
#Ici nous disons que le workflow sera déclenché à chaque push sur la branche master
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#Voici le job qui sera exécuté lorsqu'on fera le push sur la branche master
jobs:
  build:

    runs-on: ubuntu-latest #On spécifie que le job sera exécuté sur une machine ubuntu

    steps:
    - uses: actions/checkout@v3 #https://github.com/actions/checkout pour plus de détails.
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: loicsanou/springboot-ci-cd
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}